services:
  postgres:
    container_name: trackgeek-postgres
    image: postgres:13
    restart: always
    ports:
      - '20141:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trackgeek
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
networks:
  default:
    name: trackgeek
    driver: bridge